# Generated by Django 6.0.4 on 2026-04-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveSmallIntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='skills.skill')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='teams.team')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('required_level__gte', 1), ('required_level__lte', 5)), name='skillrequirement_level_1_to_5')],
                'unique_together': {('team', 'skill')},
            },
        ),
    ]
