# Generated by Django 6.0.4 on 2026-04-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('skills', '0002_skillrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('confirmed', 'Confirmed'), ('deleted', 'Deleted')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='skills.skillassignment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_history', to='employees.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='skills.skill')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
