# Generated by Django 6.0.4 on 2026-04-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skillassignmenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevelDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_descriptions', to='skills.skill')),
            ],
            options={
                'ordering': ['skill', 'level'],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 5)), name='skillleveldesc_level_1_to_5')],
                'unique_together': {('skill', 'level')},
            },
        ),
    ]
