# Generated by Django 6.0.4 on 2026-04-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skillleveldescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleTemplateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveSmallIntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_template_skills', to='skills.skill')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.roletemplate')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('required_level__gte', 1), ('required_level__lte', 5)), name='roletemplateskill_level_1_to_5')],
                'unique_together': {('template', 'skill')},
            },
        ),
    ]
