# Generated by Django 5.2.5 on 2026-04-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_roletemplate_id_alter_roletemplateskill_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roletemplate',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='skillassignment',
            options={'ordering': ['employee', 'skill']},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skill categories'},
        ),
        migrations.AlterModelOptions(
            name='skillrequirement',
            options={'ordering': ['team', 'skill']},
        ),
    ]
