# Generated by Django 5.2.5 on 2026-04-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_roletemplate_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roletemplateskill',
            options={'ordering': ['template', 'skill']},
        ),
    ]
