# Generated by Django 5.2.5 on 2026-04-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_plans', '0001_initial'),
        ('skills', '0009_alter_roletemplateskill_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='developmentgoal',
            constraint=models.CheckConstraint(condition=models.Q(('current_level__gte', 1), ('current_level__lte', 5)), name='devgoal_current_level_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='developmentgoal',
            constraint=models.CheckConstraint(condition=models.Q(('target_level__gte', 1), ('target_level__lte', 5)), name='devgoal_target_level_1_to_5'),
        ),
    ]
