# Generated by Django 5.2.5 on 2026-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('apply', 'Apply'), ('import', 'Import'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('lockout', 'Lockout'), ('logout', 'Logout')], max_length=16),
        ),
    ]
