# Generated by Django 5.2.5 on 2026-04-28 12:50

import django.db.models.deletion
from django.db import migrations, models

import certificates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_id'),
        ('skills', '0006_alter_roletemplate_id_alter_roletemplateskill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to=certificates.models.certificate_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employees.employee')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='skills.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
