# Generated by Django 5.2.5 on 2026-04-29 17:12

import django.core.validators
from django.db import migrations, models

import certificates.models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, upload_to=certificates.models.certificate_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), certificates.models.validate_file_size]),
        ),
    ]
