# Generated by Django 5.2.5 on 2026-04-30 13:00

import certificates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_file_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, upload_to=certificates.models.certificate_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), certificates.models.validate_file_size, certificates.models.validate_file_content]),
        ),
    ]
